import ftn.sbzn.PoEhelperbackend.model.Tag;
import ftn.sbzn.PoEhelperbackend.model.Build;
import java.util.Set;
import ftn.sbzn.PoEhelperbackend.model.Mods;
import ftn.sbzn.PoEhelperbackend.model.ModList;
import ftn.sbzn.PoEhelperbackend.model.Mod;
import ftn.sbzn.PoEhelperbackend.model.ItemRecommendations;


rule "fire pref body"
agenda-group "build"
salience 10
when
    $mods: Mods()
    $hmods: ModList() from $mods.bodyMods
	Tag( name == "Fire" )
	$ir: ItemRecommendations(bodyArmourSelected == true, $currentMods: bodyMods)
	$curr: ModList(prefixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.prefixes.add($hmods.findRandomPrefWithTag("Fire", $curr, $b));
    update($ir)
end	

rule "fire suf body"
agenda-group "build"
salience 10
when
    $mods: Mods()
    $hmods: ModList() from $mods.bodyMods
	Tag( name == "Fire" )
	$ir: ItemRecommendations(bodyArmourSelected == true, $currentMods: bodyMods)
	$curr: ModList(suffixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.suffixes.add($hmods.findRandomSufWithTag("Fire", $curr, $b));
    update($ir);

end

rule "Life pref body"
agenda-group "build"
salience 20
when
    $mods: Mods()
    $hmods: ModList() from $mods.bodyMods
	Tag( name == "Life" )
	$ir: ItemRecommendations(bodyArmourSelected == true, $currentMods: bodyMods)
	$curr: ModList(prefixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.prefixes.add($hmods.findRandomPrefWithTag("Life", $curr, $b));
    update($ir)
end

rule "Physical pref body"
agenda-group "build"
salience 10
when
    $mods: Mods()
    $hmods: ModList() from $mods.bodyMods
	Tag( name == "Physical" )
	$ir: ItemRecommendations(bodyArmourSelected == true, $currentMods: bodyMods)
	$curr: ModList(prefixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.prefixes.add($hmods.findRandomPrefWithTag("Physical", $curr, $b));
    update($ir)
end

rule "Caster pref body"
agenda-group "build"
salience 10
when
    $mods: Mods()
    $hmods: ModList() from $mods.bodyMods
	Tag( name == "Caster" )
	$ir: ItemRecommendations(bodyArmourSelected == true, $currentMods: bodyMods)
	$curr: ModList(prefixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.prefixes.add($hmods.findRandomPrefWithTag("Caster", $curr, $b));
    update($ir)
end


rule "Critical suf body"
agenda-group "build"
salience 20
when
    $mods: Mods()
    $hmods: ModList() from $mods.bodyMods
	Tag( name == "Critical" )
	$ir: ItemRecommendations(bodyArmourSelected == true, $currentMods: bodyMods)
	$curr: ModList(suffixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.suffixes.add($hmods.findRandomSufWithTag("Critical", $curr, $b));
    update($ir);

end

rule "Attributes suf body"
agenda-group "build"
salience 15
when
    $mods: Mods()
    $hmods: ModList() from $mods.bodyMods
	Tag( name == "Attributes" )
	$ir: ItemRecommendations(bodyArmourSelected == true, $currentMods: bodyMods)
	$curr: ModList(suffixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.suffixes.add($hmods.findRandomSufWithTag("Attributes", $curr, $b));
    update($ir);

end

rule "Aura suf body"
agenda-group "build"
salience 20
when
    $mods: Mods()
    $hmods: ModList() from $mods.bodyMods
	Tag( name == "Aura" )
	$ir: ItemRecommendations(bodyArmourSelected == true, $currentMods: bodyMods)
	$curr: ModList(suffixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.suffixes.add($hmods.findRandomSufWithTag("Aura", $curr, $b));
    update($ir);

end