import ftn.sbzn.PoEhelperbackend.model.Tag;
import ftn.sbzn.PoEhelperbackend.model.Build;
import java.util.Set;
import ftn.sbzn.PoEhelperbackend.model.Mods;
import ftn.sbzn.PoEhelperbackend.model.ModList;
import ftn.sbzn.PoEhelperbackend.model.Mod;
import ftn.sbzn.PoEhelperbackend.model.ItemRecommendations;


rule "fire pref boots"
agenda-group "build"
when
    $mods: Mods()
    $hmods: ModList() from $mods.bootsMods
	Tag( name == "Fire" )
	$ir: ItemRecommendations(bootsSelected == true, $currentMods: bootsMods)
	$curr: ModList(prefixes.size() < 3) from $currentMods
then
//    System.out.println("test");
    $curr.prefixes.add($hmods.findRandomPrefWithTag("Fire", $curr));
    update($ir)
end	

rule "fire suf boots"
agenda-group "build"
when
    $mods: Mods()
    $hmods: ModList() from $mods.bootsMods
	Tag( name == "Fire" )
	$ir: ItemRecommendations(bootsSelected == true, $currentMods: bootsMods)
	$curr: ModList(suffixes.size() < 3) from $currentMods
then
//    System.out.println("test");
    $curr.suffixes.add($hmods.findRandomSufWithTag("Fire", $curr));
    update($ir);

end
