import ftn.sbzn.PoEhelperbackend.model.Tag;
import ftn.sbzn.PoEhelperbackend.model.Build;
import java.util.Set;
import ftn.sbzn.PoEhelperbackend.model.Mods;
import ftn.sbzn.PoEhelperbackend.model.ModList;
import ftn.sbzn.PoEhelperbackend.model.Mod;
import ftn.sbzn.PoEhelperbackend.model.ItemRecommendations;


rule "fire pref boots"
agenda-group "build"
salience 10
when
    $mods: Mods()
    $hmods: ModList() from $mods.bootsMods
	Tag( name == "Fire" )
	$ir: ItemRecommendations(bootsSelected == true, $currentMods: bootsMods)
	$curr: ModList(prefixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.prefixes.add($hmods.findRandomPrefWithTag("Fire", $curr, $b));
    update($ir)
end	

rule "fire suf boots"
agenda-group "build"
salience 10
when
    $mods: Mods()
    $hmods: ModList() from $mods.bootsMods
	Tag( name == "Fire" )
	$ir: ItemRecommendations(bootsSelected == true, $currentMods: bootsMods)
	$curr: ModList(suffixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.suffixes.add($hmods.findRandomSufWithTag("Fire", $curr, $b));
    update($ir);

end

rule "Speed pref boots"
agenda-group "build"
salience 20
when
    $mods: Mods()
    $hmods: ModList() from $mods.bootsMods
	Tag( name == "Speed" )
	$ir: ItemRecommendations(bootsSelected == true, $currentMods: bootsMods)
	$curr: ModList(prefixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.prefixes.add($hmods.findRandomPrefWithTag("Speed", $curr, $b));
    update($ir)
end

rule "Speed suf boots"
agenda-group "build"
salience 10
when
    $mods: Mods()
    $hmods: ModList() from $mods.bootsMods
	Tag( name == "Speed" )
	$ir: ItemRecommendations(bootsSelected == true, $currentMods: bootsMods)
	$curr: ModList(suffixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.suffixes.add($hmods.findRandomSufWithTag("Speed", $curr, $b));
    update($ir);

end

rule "Defences pref boots"
agenda-group "build"
salience 10
when
    $mods: Mods()
    $hmods: ModList() from $mods.bootsMods
	Tag( name == "Defences" )
	$ir: ItemRecommendations(bootsSelected == true, $currentMods: bootsMods)
	$curr: ModList(prefixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.prefixes.add($hmods.findRandomPrefWithTag("Defences", $curr, $b));
    update($ir)
end

rule "Resistance suf boots"
agenda-group "build"
salience 20
when
    $mods: Mods()
    $hmods: ModList() from $mods.bootsMods
	Tag( name == "Resistance" )
	$ir: ItemRecommendations(bootsSelected == true, $currentMods: bootsMods)
	$curr: ModList(suffixes.size() < 3) from $currentMods
	$b: Build()
then
//    System.out.println("test");
    $curr.suffixes.add($hmods.findRandomSufWithTag("Resistance", $curr, $b));
    update($ir);

end