import ftn.sbzn.PoEhelperbackend.model.Tag;
import ftn.sbzn.PoEhelperbackend.model.Build;
import java.util.Set;
import ftn.sbzn.PoEhelperbackend.model.Mods;
import ftn.sbzn.PoEhelperbackend.model.ModList;
import ftn.sbzn.PoEhelperbackend.model.Mod;
import ftn.sbzn.PoEhelperbackend.model.ItemRecommendations;



rule "fire mods helm"
agenda-group "build"
when
    $mods: Mods()
    $hmods: ModList() from $mods.helmetMods
	Tag( name == "Fire" )
	$ir: ItemRecommendations(helmetSelected == true, $currentMods: helmetMods)
	$pref: ModList(prefixes.size() < 3) from $currentMods
then
    System.out.println("test");
end	

